{{- define "decodePassword" }}
  {{- $password := . }}
  {{- if or (eq $password "null") (eq $password nil) }}
    {{- "PASSWORD-NOT-YET-FOUND" }}
  {{- else }}
    {{- $password | b64dec }}
  {{- end }}
{{- end }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}-config
  namespace: customer-{{ .Values.global.customer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  NODE_NAME: delta-node
  NODE_DESCRIPTION: Experimental Deal Maker
  NODE_TYPE: delta-main
  REPO: /storage/whypfs
  DELTA_WALLET_DIR: /storage/wallet
  MODE: cluster
  {{- $dbName := "deltadb" }}
  {{- $secretNamespace := printf "customer-%s" .Values.global.customer.name }}
  DB_NAME: {{ $dbName }}
  {{- $decodedPassword := (include "decodePassword" .Values.global.customer.delta_db_password) }}
  DB_DSN: {{ printf "postgres://delta:%s@dbfws.%s/deltadb" $decodedPassword $secretNamespace }}
  {{- if (index .Values.global.products (index .Values.product)).customEnv }}
  {{ (index .Values.global.products (index .Values.product)).customEnv }}
  {{- end }}