apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}-config
  namespace: customer-{{ .Values.global.customer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
data:
  NODE_NAME: delta-node
  NODE_DESCRIPTION: Experimental Deal Maker
  NODE_TYPE: delta-main
  REPO: /storage/whypfs
  DELTA_WALLET_DIR: /storage/wallet
  MODE: cluster
  {{- $dbName := "deltadb" }}
  {{- $secretNamespace := printf "customer-%s" .Values.global.customer.name }}
  DB_NAME: {{ $dbName }}
  {{- $decodedPassword := .Values.global.customer.delta_db_password | b64dec }}
  DB_DSN: {{ printf "postgres://delta:%s@dbfws.%s/deltadb" $decodedPassword $secretNamespace }}