apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}
  namespace: customer-{{ .Values.global.customer.name }}
  labels:
    {{- include "cpi-delta.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cpi-delta.selectorLabels" . | nindent 4 }}
