{{- $sizeConfig := include "cpi-delta.getSizeConfig" . | fromYaml }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.global.customer.name }}-{{ .Values.product }}
  namespace: customer-{{ .Values.global.customer.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  labels:
    app: {{ .Values.global.customer.name }}-{{ .Values.product }}
spec:
  serviceName: {{ .Values.global.customer.name }}-{{ .Values.product }}
  podManagementPolicy: "Parallel"
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.global.customer.name }}-{{ .Values.product }}
  template:
    metadata:
      labels:
        app: {{ .Values.global.customer.name }}-{{ .Values.product }}
      annotations:
        kubernetes.io/ingress-bandwidth: {{ $sizeConfig.ingressBandwidth }}
        kubernetes.io/egress-bandwidth: {{ $sizeConfig.egressBandwidth }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: init-storage
        image: busybox
        command: ["sh", "-c", "chown 1337:1337 /storage/"]
        securityContext:
          runAsUser: 0
          runAsGroup: 0
        volumeMounts:
        - name: storage
          mountPath: /storage
      - name: init-wallet
        image: busybox
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        command:
        - sh
        - -c
        - |
          mkdir -p /storage/wallet &&
          umask 0077 &&
          if [ -z "$(WALLET_CUSTOM)" ]; then
            echo "$(WALLET_CONTENT)" | base64 -d > /storage/wallet/$(WALLET_NAME) &&
            echo >> /storage/wallet/$(WALLET_NAME) &&
            echo "$(WALLET_CONTENT)" | base64 -d > /storage/wallet/MRSWMYLVNR2A
            echo >> /storage/wallet/MRSWMYLVNR2A
          else
            echo "$(WALLET_CUSTOM)" | base64 -d > /storage/wallet/$(WALLET_NAME) &&
            echo >> /storage/wallet/$(WALLET_NAME) &&
            echo "$(WALLET_CUSTOM)" | base64 -d > /storage/wallet/MRSWMYLVNR2A
            echo >> /storage/wallet/MRSWMYLVNR2A
          fi
        env:
        - name: WALLET_NAME
          value: "{{ .Values.global.customer.walletName }}"
        - name: WALLET_CONTENT
          value: '{{ .Values.global.customer.wallet }}'
        {{- if .Values.global.customer.wallet_custom }}
        - name: WALLET_CUSTOM
          value: '{{ .Values.global.customer.wallet_custom }}'
        {{- end }}
        volumeMounts:
        - name: storage
          mountPath: /storage
      containers:
      - name: {{ .Values.product }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        workingDir: /data
        command: ["/app/delta", "daemon", "--repo=$(REPO)", "--wallet-dir=$(DELTA_WALLET_DIR)"]
        envFrom:
          - configMapRef:
              name: {{ .Values.global.customer.name }}-{{ .Values.product }}-config
        #command: ["/bin/sh", "-c", "while true; do sleep 30; done"]
        ports:
          - name: delta-http
            containerPort: 1414
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /health/ping
            port: delta-http
        resources:
          limits:
            cpu: "{{ $sizeConfig.cpuLimit }}"
            memory: "{{ $sizeConfig.memoryLimit }}"
          requests:
            cpu: "{{ $sizeConfig.cpuRequest }}"
            memory: "{{ $sizeConfig.memoryRequest }}"
        volumeMounts:
          - name: storage
            mountPath: /storage
          - name: {{ .Values.global.customer.name }}-{{ .Values.product }}-db
            mountPath: /data
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: {{ .Values.global.customer.name }}-{{ .Values.product }}-storage
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.global.customer.name }}-{{ .Values.product }}-db
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "1Gi"
